apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sentiment-collector
  name: sentiment-collector
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    io.kompose.service: sentiment-collector
