apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sentiment-analytic-go
  name: sentiment-analytic-go
spec:
  ports:
  - name: "8444"
    port: 8444
    targetPort: 8444
  #type: LoadBalancer
  type: NodePort
  selector:
    io.kompose.service: sentiment-analytic-go
