apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv1-block
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: scw-bssd
  volumeMode: Block